-- Atomically claim a job from the pending queue
-- KEYS[1] = pendingKey
-- KEYS[2] = processingKey
-- ARGV[1] = jobKeyPrefix (e.g. "queueName:job:")
-- ARGV[2] = workerId
-- ARGV[3] = leaseMs
-- ARGV[4] = now (epoch ms)
-- ARGV[5] = claimToken (UUID generated by caller)

local pendingKey = KEYS[1]
local processingKey = KEYS[2]
local jobKeyPrefix = ARGV[1]
local workerId = ARGV[2]
local leaseMs = tonumber(ARGV[3])
local now = tonumber(ARGV[4])
local claimToken = ARGV[5]

-- Pop the oldest job from the pending list (RPOP = FIFO with LPUSH)
local jobId = redis.call('RPOP', pendingKey)
if not jobId then
    return nil
end

local jobKey = jobKeyPrefix .. jobId
local exists = redis.call('EXISTS', jobKey)
if exists == 0 then
    return nil
end

local leaseUntil = now + leaseMs

-- Update job hash with claim metadata
redis.call('HSET', jobKey,
    'status', 'processing',
    'workerId', workerId,
    'claimedAt', now,
    'leaseUntil', leaseUntil,
    'claimToken', claimToken,
    'updatedAt', now,
    'processingStartedAt', now
)
redis.call('HINCRBY', jobKey, 'attempts', 1)

-- Add to processing sorted set with leaseUntil as score (enables lease-based recovery)
redis.call('ZADD', processingKey, leaseUntil, jobId)

-- Return full job data as JSON
local jobFields = redis.call('HGETALL', jobKey)
local job = {}
for i = 1, #jobFields, 2 do
    job[jobFields[i]] = jobFields[i + 1]
end
return cjson.encode(job)
